### PR TITLE
Add Format

### LINKED ISSUE #10: Add an encoder
Would you be interested in a patch adding an encoder?

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/luxifer/ical/issues/10

### CODE REVIEW

**Comment by luxifer** [comment]
Looks great! Can you try to parse an ical fixture (from the folder), then format it with your method, and re parse what you format, just to make sure the parsed fixture and the parsed format are strictly equal? this way this parser/formater will be sort of turing complete

**Comment by emersion** [comment]
Unfortunately this won't work great, because a `map` is used to store fields, hence fields will get re-ordered. Preserving fields (and params) ordering would require adding some sort of [map with a list of fields attached](https://github.com/emersion/go-message/blob/master/textproto/header.go#L24).

**Comment by emersion** [comment]
Ah, but you mean comparing the parsed values? Yeah, can definitely do that!

**Comment by luxifer** [comment]
Yes that's what I mean. Thanks ;)

Florent Viel

Le mar. 18 févr. 2020 à 11:30, Simon Ser <notifications@github.com> a
écrit :

**Comment by emersion** [comment]
Hmm, so one issue is that there are two sources of truth: the `Properties` fields and the parsed fields (e.g. `Event.Timestamp`). When formatting a field, the parsed field value is currently used because it might have been updated by the user, however since some fields are redundant (`Timestamp` vs `EndTime`) the result won't be equal to the original.

I'm tempted to replace parsed fields with helper functions like [`net/mail.Header`](https://golang.org/pkg/net/mail/#Header) does.

**Comment by emersion** [comment]
Ended up writing my own lib.

**Pull request closed without merging**
